version: "3"

services:
  web:
    restart: unless-stopped
    build: .
    environment:
      PORT: "8000"
    ports:
      - "8000:8000"
    env_file: ./backend/.env
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
